### ISSUE TITLE
Instructions part 16-resources, Connecting to Nodes does not work on all clusters.

### ISSUE THREAD

**Issue by kamil963** [carpentries-incubator/hpc-intro#103]
In Instructions part 16-resources, Connecting to Nodes does not work on all clusters. 

Depending on exact OS versions deployed on cluster nodes these instructions do not work. 

Using ssh to connect to the cluster node on which your job runs results in 
your ssh session being in a different cgroup (if cgroups are used) from your job.
Depending upon your OS, these cgroups will potentially have a different process namespaces, (via the way /proc fileystem is mounted ).

If this is true you cannot see the jobs processes via commands such as ps or top from the ssh session as they are in different namespaces. 

The universal fix is to attach to the job via srun instead of sshing into the node.
The instructions should say please attach to the running job 
"srun --jobid <jobid> --pty bash"

In that case your session is part of your job and therefore in the same cgroup and consequently process namespace. Therefore ps and top work.

**Comment by psteinb** [comment]
@kamil963 thanks for pointing out this deficiency. I think most of the material in this repo assumes that cgroups are NOT used on the cluster at hand. We need to take this into account. 

Further, we are currently working on an updated lesson outline for this material in order to start working on it collaboratively. I have my doubts that [16-resources.md](https://github.com/hpc-carpentry/hpc-intro/blob/efadc7ec3562f39d76f145e861ecc1796b8cf692/_episodes/16-resources.md) will survive this refactoring. 

From a (or my) teaching point of view, it contains too many technical terms without proper introduction. There is a good reason to have such a discussion on how to estimate the resource requirements of a program on a *NIX machine. If the place is here and if the tools used are the best is up for debate.

**Comment by psteinb** [comment]
@aturner-epcc @tkphd @ChristinaLK 
How should we proceed? Should we a apply a fix? Or should we leave it as is?

**Comment by aturner-epcc** [comment]
@psteinb I was a little uncomfortable with this part when I was doing the recent update to make the lesson configurable. I thought about trying to do something but decided it was outwith the remit of what I was working on at the moment.

I do think this needs to be addressed and the episode 16 is one of the weakest parts of the current lesson. In my opinion, it is useful for users to know how to estimate resources they are using (even roughly) but, as illustrated by this issue, the ways of doing this are very variable based on the HPC system setup and which scheduler is being used.

Can we agree on what would be the minimum things that it is useful for a user to be able to query in terms of resource use and then see if they are queryable on the majority of systems at runtime?

In my mind, it is useful if users can ask:

* How long has my job been running for (walltme)? this is easy on all systems I think
* How many nodes (cores?) is my job running on? Nodes are easy on all systems and cores should also be possible (at least for the resources requested in the job, if not those actually used...). Querying what you are **actually** using is more difficult on some systems.
* How much memory am I using? Usually OK when the scheduler is tightly coupled to the resources (e.g. SLURM in usual configuration), can be difficult for other schedulers (e.g. PBS Pro), may be a weird command (e.g. Cray ALPS)
* How much storage space am I using? Easy if you know what files your job is producing as you can use 'ls' or 'du' (with caveat of large tree walks).

Having written this basic list I am actually more optimistic that this could be fixed without too many problems. All of the above are relatively easy to include with the complications being memory and *actual* node/core use and should be able to be addressed without resorting to using tools such as 'top' etc as we can get the information from the scheduler (which is actually the right way to do it rather than hacking logins to compute nodes).

**Comment by tkphd** [comment]
`17-resources.md` has been reworked; this no longer applies.
