### ISSUE TITLE
splitting this lesson into hpc-shell and hpc-intro

### ISSUE THREAD

**Issue by psteinb** [carpentries-incubator/hpc-intro#19]
As discussed, with @aturner-epcc and many others from this team, I wanted to start discussing splitting this lesson. The core reason is, that I am not sure whether to start merging from [hpc-novice](https://github.com/swcarpentry/hpc-novice) before or after the split.

**Comment by ChristinaLK** [comment]
I would split out 3,4,5,6 into hpc-shell

And replace them with a shell "placeholder" page in hpc-intro which refers to the hpc-shell lesson.  

I'd do the PRs after.

**Comment by psteinb** [comment]
indeed, I'd say 0{2,3,4,5,6} go into hpc-shell. The rest stays here and potentially will be renamed to make mixing and matching easier. Even though I think, if the episodes in hpc-shell start with 00? (to allow more than 9 episodes) and the ones here go by 10?, we should be fine. thoughts?

**Comment by psteinb** [comment]
Any other opinions? Otherwise, I'd start working on this tomorrow.

**Comment by symulation** [comment]
3 through 6 are the hpc-shell components for sure.

What to do with #1 and #2 is the question.  Arguably both belongs most properly in "hpc-novice" since the background assumption needs to be that participants have never logged in before but #2, at least, is also necessary for "hpc-shell" since some users might not actually have a shell on their local machine and we want to get them used to working remotely.  This makes things awkward because typically lessons are completely standalone but the setup here requires the connection in both cases.

While it adds to the number of lessons by producing a very short lesson perhaps the way forward is to turn #1 and #2 into "hpc-connect", 2-6 into "hpc-shell" and the remainder into "hpc-novice"?  This avoids the problems of either duplicating across lessons or cherry-picking an episode from another lesson.  

Thoughts?

**Comment by psteinb** [comment]
So here is my working assumption for the next days, that I believe we agreed upon (please provide feedback if needed):

1. create a new repo `hpc-shell`
2. keep using this repo `hpc-intro`, but strip it down

NB. For me there is no `hpc-novice` anymore. What do you mean by this?

Here is my (improved) rational:
- `00-hpc-intro.md`, must stay in here no doubt ... but parts of it can be shared with hpc-shell to keep the frame for HPC
- `01-connecting.md`, stays in `hpc-intro`
- `02-navigation.md`, goes into `hpc-shell` as there is (at this point) no reference to a cluster, so the content is mostly around file system navigation
- `03-files.md` goes into `hpc-shell`
- `04-wildcards-pipes.md` goes into `hpc-shell`
- `05-scripts.md` goes into `hpc-shell`

Anything below goes into or stays in `hpc-intro`.
`11-cluster.md, 12-scheduler.md, 13-modules.md, 14-transferring-files.md, 15-resources.md, 16-responsiblity.md`

**Comment by symulation** [comment]
I was calling "hpc-intro" "hpc-novice".  Not sure why.  Just how it came out I guess.  =)

If `hpc-intro` is going to get `01-connecting` then I suspect that we'll need to put a link / connection to `01-connecting` at the beginning of `hpc-shell`.  Possibly put an optional connection back to `hpc-shell` from `01-connecting` too.

I'm still wondering about having an `hpc-connect` that would stand on its own but I'm willing to allow that is hairsplitting (or the like) on my part.

**Comment by jstaf** [comment]
I think we can include the connecting episode in both repositories. Chances are that when taught together the students are going to need to logon again for the second session, it doesn't hurt to review things. 

One less thing to delete in the the new repo :)

**Comment by symulation** [comment]
Maybe doubling up is the best option for now but the 2x maintenance is a frightening prospect, especially once they fall out of sync.

Long term it should be in just one place.  Either its own `hpc-connect` repo _or_ in either `hpc-shell` or `hpc-intro`.  

As I think this over I'm beginning to think that _if_ we go with the option of putting the connection episode into one of the existing repos then putting it in `hpc-shell` is the better way to go.  Why?  A workshop that is using `hpc-shell` will have the newer users and having them ostensibly jump ahead and then back is additional cognitive load that they don't need.  Additionally, built into this hopping around is an implicit "You should already know this shell stuff but since you don't we'll go back and cover it."  A better implicit narrative for new users would be, "shell first and then the hpc specifics is just how things are."  For workshops with more seasoned shell users, having the connect content in the `hpc-shell` lesson would result in an implicit narrative like, "You're special because you already know the shell content so we'll just connect and then skip ahead."  As long as they _really_ know the shell content then they're good to go too and both types of participants win.

**Comment by psteinb** [comment]
I created the hpc-shell repo:
https://github.com/hpc-carpentry/hpc-shell/pull/1

**Comment by ChristinaLK** [comment]
I like @psteinb's outline from yesterday!

**Comment by ChristinaLK** [comment]
I will go look at the PR.

**Comment by ChristinaLK** [comment]
@symulation my thought has been that whoever's teaching could clone the `hpc-intro` repo and then slot in shell material of their choice ( `hpc-shell`,swc's `shell-novice`, or nothing, if teaching an advanced group) at whatever point they see fit in the `hpc-intro` (probably right after the intro + connecting to the cluster).  

So I think `hpc-shell` should be generic shell material and connecting/transferring files should be in `hpc-intro` because those are shell skills specifically needed for using a cluster.

**Comment by Sabryr** [comment]
I see that "hpc-carpentry/hpc-shell" is created, so does this repo  become hpc-intro ? or will that be created (and this one deprecated).  
Either way the intro and scope should be reorganised (e.g. ...By the end of this workshop, students will know how to: ... How Programming language introduction/review, Introduction to parallel programming etc.. not relevant any more). Could send PR on this but you had explicitly mentioned until the lesson strategy is organised PR not welcome.

**Comment by ChristinaLK** [comment]
@Sabryr I think we've determined the lesson strategy.  This repo is going to stay `hpc-intro` and can be integrated with `hpc-shell` as needed (giving people the option to include shell tools in the training or not, as they want).  

So if you wanted to submit a PR that modifies the intro/scope, that would be welcome.

**Comment by psteinb** [comment]
see #30
