### ISSUE TITLE
Visualize bandwidth vs. latency in data transfers

### ISSUE THREAD

**Issue by tkphd** [carpentries-incubator/hpc-intro#221]
In Ep. 18, possibly a general "bandwidth vs latency" paragraph in the
context of scaling would be useful? Amdahl's law, even?

**Comment by tkphd** [comment]
Spun out from #185.

**Comment by mikerenfro** [comment]
Looks like this is Episode 18 now. Just to save others the confusion I had.

**Comment by reid-a** [comment]
Another reason to use names to describe lessons, and not sequence numbers.

**Comment by mikerenfro** [comment]
In the broader context of bandwidth and latency for disk and network I/O, I've got a figure attached that may help visualize things: [disk-network-bandwidth-latency.pdf](https://github.com/hpc-carpentry/hpc-intro/files/5435825/disk-network-bandwidth-latency.pdf). Each of the components on the figure is connected by a black line of width proportional to the interface bandwidth, and a white line of width proportional to the data transferred along that interface.


```latex
\documentclass{standalone}
\usepackage{amsmath}
\usepackage{tikz}
\usetikzlibrary{positioning}
\begin{document}
\newcommand\dataline[5]{%
\draw [line width=#1 mm] (#3) to [#5] (#4);%
\draw [line width=#2 mm,white] (#3) to [#5] (#4);%
}
\begin{tikzpicture}%[]
[disk/.style={rectangle,draw=black!50,fill=black!20,align=left},
 controller/.style={rectangle,draw=red!80,fill=red!20,align=left},
 nic/.style={rectangle,draw=blue!80,fill=blue!20,align=left},
 switch/.style={rectangle,draw=green!80,fill=green!20,align=left}]
\node[disk]       (disk 1)                                     {SSD 1, 12 Gb/s interface,\\ sends 4 Gb/s bandwidth,\\ 4 ms latency};
\node[disk]       (disk 2)          [below=of disk 1]          {SSD 2, 12 Gb/s interface,\\ sends 4 Gb/s bandwidth,\\ 4 ms latency};
\node             (dots)            [below=of disk 2]          {$\vdots$};
\node[disk]       (disk 9)          [below=of dots]            {SSD 9, 12 Gb/s interface,\\ sends 4 Gb/s bandwidth,\\ 4 ms latency};
\node[disk]       (disk 10)         [below=of disk 9]          {SSD 10, 12 Gb/s interface,\\ sends 4 Gb/s bandwidth,\\ 4 ms latency};
\node[controller] (raid controller) [right=5cm of dots]        {RAID 10 controller, 63 Gb/s interface,\\ forwards 40 Gb/s bandwidth};
\node[nic]        (server nic)      [right=of raid controller] {server network card, 56 Gb/s interface,\\ forwards 40 Gb/s bandwidth};
\node[switch]     (switch)          [right=of server nic]      {network switch, 56 Gb/s interfaces,\\ forwards 40 Gb/s bandwidth,\\ 0.004 ms latency};
\node[nic]        (node 1 nic)      [above=of switch]          {node 1 network card, 56 Gb/s interface,\\ receives 20 Gb/s bandwidth};
\node[nic]        (node 2 nic)      [below=of switch]          {node 2 network card, 56 Gb/s interface,\\ receives 20 Gb/s bandwidth};
\dataline{1.2}{0.4}{disk 1}{raid controller}{out=0, in=180}
\dataline{1.2}{0.4}{disk 2}{raid controller}{out=0, in=180}
\dataline{1.2}{0.4}{disk 9}{raid controller}{out=0, in=180}
\dataline{1.2}{0.4}{disk 10}{raid controller}{out=0, in=180}
\dataline{6.3}{4.0}{raid controller}{server nic}{}
\dataline{5.6}{4.0}{server nic}{switch}{}
\dataline{5.6}{2.0}{switch}{node 1 nic}{}
\dataline{5.6}{2.0}{switch}{node 2 nic}{}
\end{tikzpicture}
\end{document}
```

**Comment by reid-a** [comment]
This is a nice addition, I think it has significant utility for connecting the ideas of bandwidth and latency to the kinds of decisions you need to make when setting up an HPC workflow on an actual system, which is the core of the lesson.

I think there's a bunch of work still to do on the text to properly support this figure, introducing bandwidth and latency generally, outside of the computer context.

Since we have already introduced the restaurant analogy, possibly that could be re-used? You can increase the restaurant's bandwidth by scaling up tables, cooks, waiters, and bussers, but you can't change the amount of time it takes to cook a meal, so while aggregate restaurant throughput can be arbitrarily high, each customer's "dwell time" is fixed, nobody gets their food any faster no matter how many tables there are. This can kill you -- if the meal prep time is many hours, so that nobody gets their meal in the course of an evening, your restaurant will fail no matter how much bandwidth you add.

I have seen a few other examples.

One is, "why don't you take a jet plane to work?". Jet planes have phenomenal bandwidth, they can move hundreds of people thousands of miles in just a few hours, so why not use them to commute? The answer is latency, of course, jet airplanes require special facilities to take off and land, and you can only realize the efficiencies by coordinating passengers a plane-load at a time.

The other famous example is Andrew Tanenbaum's [famous quote](https://en.wikiquote.org/wiki/Andrew_S._Tanenbaum) about a station-wagon full of tapes. This is indeed a high-bandwidth data transfer solution, but again it's got bad latency problems -- just because the station wagon full of tapes has arrived at my facility doesn't mean that I have the data, I have to mount the tapes to tape drives and read them before I can examine it.

The general idea, of course, is to complement @mikerenfro 's terrific figure with some background info.
