### ISSUE TITLE
Deployment errors on non-canonical sites due to CNAME change?

### ISSUE THREAD

**Issue by reid-a** [carpentries-incubator/hpc-intro#284]
When pushing recent changes up to my local fork of the repo, I got a message from github that the CNAME I requested, "hpc-intro.hpc-carpentry.org", is already taken, and not available to me.

I was directed to a [trouble-shooting page](https://docs.github.com/en/github/working-with-github-pages/troubleshooting-custom-domains-and-github-pages#cname-errors), which describes the issue in more detail.

Operationally speaking, this is a benign error, I don't really want my page to render on that URL, so I am not bothered by its failure to do so.

It's unclear to me how to avoid this. As far as I can tell, the CNAME file has to be part of the repo in order for the custom URL mechanism to work at all, and as part of the repo, it has to be reproduced in github forks of the repo, where it is doomed to fail. Thus, it seems that all the github forks are going to be broken, which doesn't seem right either.

**Comment by reid-a** [comment]
See also this [StackOverlow](https://stackoverflow.com/questions/35096128/how-to-prevent-a-cname-file-from-ever-being-forked) question and (negative) answer. It's five years old, though, so the situation may have changed.

**Comment by tkphd** [comment]
In your fork's Settings, under the Options tab (open by default), scroll down to the GitHub Pages block. Anything meaningful you can set there?

**Comment by reid-a** [comment]
Nothing obvious, although the CNAME error is repeated there.

Are others seeing this? If it's just me, then some kind of sane config solution is maybe possible.

**Comment by reid-a** [comment]
Addendum (not a solution, alas): You can change which branch you use as the source for your site, and the drop-down has a "None" option, but if you select it, the site pops up a message that says that in order to unpublish your site, you have to delete the gh-pages branch. You can also select which folder to build from, and it offers "/docs" as an option, but selecting this causes a different error, it complains (correctly) that the /docs folder does not exist.

**Comment by tkphd** [comment]
Strange. My fork publishes to my personal website, apparently without a CNAME entry. I have no recollection how I configured that, beyond entering the URL in the GitHub settings...

Ah, I set the CNAME record with my domain registrar. @ocaisa is this an option?

**Comment by tkphd** [comment]
Oh! I spoke too soon. After pushing the updated site, my fork is now throwing the "CNAME already taken" warning as well. This could generate some tedious email traffic.

**Comment by reid-a** [comment]
There is also an unpromising [message[(https://github.community/t/need-help-with-jekyll-github-project-page-and-team-git-workflow/10440) from the Github community, where the "solution" is basically a description of the problem.

There is a suggestion farther down that page about using CI hooks to manage this data -- that's probably where the solution lies, if we decide to engage.

**Comment by reid-a** [comment]
Possibly if @ocaisa makes the CNAME entry with his domain registrar, we can remove the CNAME file from the repo, and then main site will work as intended *and* forks will not be broken?

**Comment by ocaisa** [comment]
I think the issue now is that because the lesson is not under our organisation it can't appear like `hpc-carpentry.org/hpc-intro` (which happens be default I believe once you set up the custom domain as your organisation domain). That only leaves us the sub-domain option and my understanding is that that has to have a CNAME entry in the repo and the registrar.

**Comment by ocaisa** [comment]
For example, look at the HPC shell lesson, that already appears at https://hpc-carpentry.github.io/hpc-shell/ , so if I configure `https://hpc-carpentry.github.io` to be served under `https://www.hpc-carpentry.org/` then there is no need to set the CNAME per lesson (not currently the case, but we should probably do that). This doesn't help us with `hpc-intro` because the that is now under the `carpentries-incubator` organisation.

I don't see a way around this, I think we need to revert the change. The whole idea of the lesson is that people will fork it and customise it, we can't be making that seem broken by default.

**Comment by tkphd** [comment]
Ohh, right, we're serving hpc-carpentry.org from hpc-carpentry/hpc-carpentry.org with one CNAME record (?), which complicates serving a lesson from the carpentries-incubator org?

I'm not well-enough versed on how CNAME records work to know what's possible. I do know that, for my own purposes, I have set the CNAME records with my domain registrar, instead of as files stored in the GitHub repositories themselves, and it seems to work. If that's at all an option, it would help reduce some occasional warning traffic. If that's not enough of a motivation, that's understandable.

**Comment by reid-a** [comment]
Just in the interests of clarity, the hpc-carpnetry.org assignment is an A record.

According to [DNS checker](https://dnschecker.org/all-dns-records-of-domain.php?query=hpc-intro.hpc-carpentry.org&rtype=ANY), the hpc-intro.hpc-carpentry.org sub-name is also an A record.

I'm not enough of a DNS expert to know exactly what this means, but there might be some maneuvering room?

**Comment by ocaisa** [comment]
Yes, that's the way I set it up because I thought I had to according to the GitHub docs, maybe because it is a subdomain I can just use a CNAME record instead...I will try it out tomorrow, but beware I don't really know what I am doing

**Comment by tkphd** [comment]
You're in good company! :confused:

**Comment by reid-a** [comment]
Any news? As of this writing, there's a two-day-old comment saying a solution attempt will be made "tomorrow" -- did it go? How didi it go?

**Comment by ocaisa** [comment]
I've been looking at this and I don't think it is possible to do what we want:
![Screenshot 2021-02-12 11 53 30](https://user-images.githubusercontent.com/3840437/107760611-59f1b980-6d2a-11eb-9f06-0a0f9444a1cc.png)
The reason is that we can't use `carpentries-incubator.github.io/hpc-intro` in the CNAME record, we can only use `carpentries-incubator.github.io`. So there is no way to point directly to the lesson (unless the lesson has it's own domain already...which it can't have).

**Comment by ocaisa** [comment]
For now, I've kept the current behaviour but I believe that we should remove the CNAME file and accept the lesson URL is going to be under `carpentries-incubator.github.io/hpc-intro`

**Comment by ocaisa** [comment]
Best we can do is add a redirect under `hpc-carpentry.org/hpc-intro` maybe

**Comment by tkphd** [comment]
Would it break a bunch of things to set the CNAME target to `carpentries-incubator.github.io`, without specifying the `/hpc-intro` part? That would certainly *allow* any repo on carpentries-incubator to set hpc-carpentry.org as the deploy address, but I doubt anyone would. I don't know enough about how this works to know what would go wrong.

**Comment by ocaisa** [comment]
Added the redirect in https://github.com/hpc-carpentry/hpc-carpentry.org/pull/9
