### ISSUE TITLE
introduce SSH keys

### ISSUE THREAD

**Issue by tkphd** [carpentries-incubator/hpc-intro#333]
In our lesson, we use SSH with passwords, which is not the best practice and, on many systems, is not allowed. Connection with a public key, guarded with a strong passphrase, is greatly preferred.
HPC Shell goes in depth on SSH keys. We should introduce it in the introduction. The logical place for this is after connecting the first time, using a passphrase: at that point, `.ssh` on the remote should exist, and the machinery is in place to `rsync` a public key. Discussion does not need to be deep, we simply require a stronger-than-default set of flags supported by all reasonably modern machines.

How's this:

```bash
ssh-keygen -a 100 -b 4096 -t rsa
```

* `-a 100`: run the key derivation function (KDF) 100 times. Default is 16.
* `-b 4096`: generate a 4096-bit key. Default for RSA (the default cipher) is 2048.
* `-t rsa`: use the RSA cryptosystem. This is probably the default.

**Comment by tobyhodges** [comment]
I would like extra sentence for each point (or at least the first two, as they are changes from the default) explaining why you are choosing this value for each option. Something as concise as "This will make the key code larger and therefore even harder to guess" would be adequate, I think.

**Comment by tkphd** [comment]
Good call, yes!

**Comment by bkmgit** [comment]
Related to https://github.com/carpentries-incubator/hpc-intro/issues/164

An introduction is in hpc shell:
http://www.hpc-carpentry.org/hpc-shell/01-connecting/index.html
 Do we need it in both places?

**Comment by mikerenfro** [comment]
My initial assumption was that I'd be able to run a standard Software Carpentry workshop on Shell, Git, and Python, and then follow it up with the hpc-intro lessons, rather than requiring everyone to go through hpc-shell. If that's the case, then a minimal number of ssh lessons in hpc-intro would be helpful.

Alternatively, if someone had already run through hpc-shell in its entirety before starting hpc-intro, they could possibly skip the ssh lessons in hpc-intro.

**Comment by bkmgit** [comment]
If the login information in hpc-shell is sufficient, can also put it into hpc-intro.
