### ISSUE TITLE
Add some  material on environment variables?

### ISSUE THREAD

**Issue by SJaffa** [carpentries-incubator/hpc-intro#428]
We had a comment in the feedback from our [recent workshop](http://github-pages.ucl.ac.uk/2022-11-08-UCL-HPCC/) that some material on environment variables would have been useful. I think that could be relevant to lots of learners as (in my experience in astronomy) documentation for installing scientific software often mentions "set these environment variables" without much explanation of how or where to set them.

We mention variables in job scripts but maybe could add something about setting them just once on the command line, and setting them in `.bashrc` or similar to have them persist between sessions (although introducing `.bashrc` might be overload?)

**Comment by ocaisa** [comment]
When I saw this I thought "Isn't that already covered under the Environment Modules episode?", and it turns out that it is used, but not really explained. Then I went looking around as I was sure I'd seen that content somewhere and I found more detailed content in our (now archived) [HPC Shell lesson](https://www.hpc-carpentry.org/hpc-shell/05-scripts/index.html#shell-variables) and also [in the Shell Extras lesson](https://carpentries-incubator.github.io/shell-extras/08-environment-variables/index.html).

We decided a while ago to archive the HPC Shell lesson and just use the Carpentries Shell lesson as a prereq, and [transcribe in the additional valuable content from HPC Shell](https://github.com/carpentries-incubator/hpc-intro/pull/373). We overlooked the content on environment variables at that point.

Looking at things now. I think the right place to do this is still in the episode on accessing software. The issue I have with that section is that there are multiple commonly used ways to access software: environment modules, conda, spack environments, containers,...). It's another place where the lesson may diverge for different sites, and it would be nice if we did our best to minimise that. 

The nice thing is that most of these (except containers) are using environment variables to modify the users environment, so we may be better off focusing (at least initially) on environment variables at the start of this episode as the common ground. I'd also see it as an opportunity to show how you can potentially influence the behaviour of a program by using environment variables (this is true for Slurm so it will be easy to show an example of this).
