### ISSUE TITLE
filesystems vary widely

### ISSUE THREAD

**Issue by baberlevi** [carpentries-incubator/hpc-intro#59]
12-cluster says:

> This is an important point to remember: files saved on one node (computer) are available everywhere on the cluster!

That statement seems overly broad - we have things like /tmp and /scratch that may or may not be shared in some way across nodes. I'd probably just remove this sentence from this section & address it in a section about filesystems where it can be explained with more detail

**Comment by tkphd** [comment]
The statement is overly broad, but the caveat is overly specific. I have yet to use a cluster *without* a parallel filesystem, `/scratch` is sometimes local and sometimes parallel, and use of `/tmp` is an advanced topic. I would prefer to rephrase the existing statement, rather than eliminating it, because it *is* an important concept. This could also be addressed in the extras.

**Comment by bkmgit** [comment]
Not relevant to the current version of the lesson. File system performance is important, but for a new user who is likely using upto 10s of cores, it is probably not the most relevant issue. This could be addressed in a later module or in software specific workflows. Issue can probably be closed.

**Comment by tkphd** [comment]
I disagree. While filesystem *performance* is not relevant, it is important to understand where data resides and how it is accessed by the nodes. That being said, Ep. 12 has been updated substantially. It now mentions the possibility of back-end servers providing access to the same files across all nodes, and inserts a caveat that the things one node writes *may* be visible to all others.
